products:
  handler: src/functions/api/products.handler
  events:
    - http:
        path: products
        method: get
        authorizer: verifyToken
        cors: true
    - http:
        path: products
        method: post
        authorizer: verifyToken
        cors: true
    - http:
        path: products
        method: put
        authorizer: verifyToken
        cors: true
    - http:
        path: products/{id}
        method: get
        authorizer: verifyToken
        cors: true
    - http:
        path: products/{id}
        method: delete
        authorizer: verifyToken
        cors: true
    - http:
        path: products/all
        method: get
        authorizer: verifyToken
        cors: true
productsByCompanyIdPublic:
  handler: src/functions/api/products.listByCompanyId
  events:
    - http:
        path: products/public/{companyId}
        method: get       
        cors: true 

productsByCompanyIdAndIdPublic:
  handler: src/functions/api/products.getByCompanyId
  events:
    - http:
        path: products/public/{companyId}/{id}
        method: get       
        cors: true 