products:
  handler: src/functions/products.list
  events:
    - http:
        path: products
        method: get
        authorizer: verifyToken
        cors: true 
productsById:
  handler: src/functions/products.listById
  events:
    - http:
        path: products/{id}
        method: get
        authorizer: verifyToken
        cors: true 
productsCreate:
  handler: src/functions/products.create
  events:
    - http:
        path: products
        method: post
        authorizer: verifyToken
        cors: true  
productsUpdate:
  handler: src/functions/products.update
  events:
    - http:
        path: products
        method: put
        authorizer: verifyToken
        cors: true 
productsDelete:
  handler: src/functions/products.delete
  events:
    - http:
        path: products/{id}
        method: delete
        authorizer: verifyToken
        cors: true 
productsListAll:
  handler: src/functions/products.listAll
  events:
    - http:
        path: products/all
        method: get
        authorizer: verifyToken
        cors: true 

productsImport:
  handler: src/functions/productsImport.import
  timeout: 600 
  events:
    - http:
        path: products/import
        method: post
        authorizer: verifyToken
        cors: true 