eventsBridgeUpdate:
  handler: src/functions/api/eventsBridge.update
  events:
    - http:
        path: services
        method: put
        authorizer: verifyToken
        cors: true 
eventsBridgeGet:
  handler: src/functions/api/eventsBridge.get
  events:
    - http:
        path: services
        method: get
        authorizer: verifyToken
        cors: true
sendEmailQueue:
  handler: src/functions/queue/sendEmail.handler
  timeout: 600 
  memorySize: 512
  events:    
    - sqs:       
        arn:
          Fn::GetAtt:
            - SendEmailQueue
            - Arn
backupEvent:
  handler: src/functions/events/backup.handler
  timeout: 600 
  memorySize: 512
  environment:
    bucketName: ${self:custom.bucketPrivate}
  events:    
    - eventBridge:
        name: "${self:service}-${opt:stage, self:provider.stage}-backup"
        description: Servico que faz backup do banco de dados
        schedule: cron(30 4 * * ? *) # 1h30 de todos dias hora BR
    - http:
        path: services/run-backup
        method: get        
        cors: true 