Resources:
    PublicSystemBucket: # nome variável
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketPublic}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
    PrivateSystemBucket: # nome variável
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketPrivate}