#Grupos de usuários do sistema
Resources:
    CognitoUserPoolGroupAdmin:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Super-usuário, pode executar todas as tarefas dos outros usuários, e mais gerenciamento de usuários no sistema (criar/editar/remover)"
        GroupName: "Administrador"
        UserPoolId:
          Ref: UserPool #Refere-se ao grupo de usuários criado acima
    CognitoUserPoolGroupUsers:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Permissão para usuário gerenciar usuários do sistema"
        GroupName: "Usuarios"
        UserPoolId:
          Ref: UserPool #Refere-se ao grupo de usuários criado acima
    CognitoUserPoolGroupProducts:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Permissão para usuário gerenciar Produtos"
        GroupName: "Produtos"
        UserPoolId:
          Ref: UserPool #Refere-se ao grupo de usuários criado acima
    CognitoUserPoolGroupRomanians:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Permissão para usuário gerenciar Romaneios"
        GroupName: "Romaneios"
        UserPoolId:
          Ref: UserPool #Refere-se ao grupo de usuários criado acima        
    CognitoUserPoolGroupSales:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Permissão para usuário gerenciar Vendas"
        GroupName: "Vendas"
        UserPoolId:
          Ref: UserPool #Refere-se ao grupo de usuários criado acima        